name: Publish Docker image

on:
    push:
        tags:
            - 'dockerImage.v.*'

jobs:
    build:
        name: Build
        if: "!contains(github.event.head_commit.author, 'action@github.com')"
        runs-on: ubuntu-latest
        steps:
            - name: set env
              run: echo BRANCH=$(echo -n "${GITHUB_REF#refs/heads/}") >> $GITHUB_ENV
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 14.18.3
            - run: npm i
            - name: test and build
              run: |
                  echo "127.0.0.1 localhost" | sudo tee -a /etc/hosts
                  echo "fs.inotify.max_user_watches=524288" | sudo tee -a /etc/sysctl.conf
                  npm run build
            - uses: actions/upload-artifact@v2
              with:
                  name: buildfiles
                  path: build/**/*
    push_to_registry:
        needs: [build]
        name: Push Docker image to GitHub Packages
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Download buildfiles artifact
              uses: actions/download-artifact@v2
              with:
                  name: buildfiles
            - name: Push to GitHub Packages
              uses: docker/build-push-action@v1.1.1
              with:
                  username: ${{ secrets.GH_PACKAGE_RELEASE_USER }}
                  password: ${{ secrets.GH_PACKAGE_RELEASE_TOKEN }}
                  registry: docker.pkg.github.com
                  repository: virtualidentityag/vi-saas-admin/frontend-image
                  tag_with_ref: true
